#include "config.h"

#ifndef SAVE_H
#define SAVE_H

//======== File Format =======//
#define FORMAT_VERSION 0.2
#define OFFSET_SIZE 4
#define LEN_SIZE 4

#define LEVEL_HEADER_NAME_OFFSET 0
#define LEVEL_HEADER_NAME_SIZE 256

#define LEVEL_HEADER_AUTHOR_OFFSET 256
#define LEVEL_HEADER_AUTHOR_SIZE 256

//========== METADATA-WALLS
#define LEVEL_HEADER_WALLS_OFFSET 512
#define LEVEL_HEADER_WALLS_OFFSET_SIZE OFFSET_SIZE

#define LEVEL_HEADER_WALLS_LEN_OFFSET 516
#define LEVEL_HEADER_WALLS_LEN_SIZE LEN_SIZE

//========== METADATA-ENEMIES
#define LEVEL_HEADER_ENEMIES_OFFSET 520
#define LEVEL_HEADER_ENEMIES_OFFSET_SIZE OFFSET_SIZE

#define LEVEL_HEADER_ENEMIES_LEN_OFFSET 524
#define LEVEL_HEADER_ENEMIES_LEN_SIZE LEN_SIZE

//========== METADATA-WARPZONES
#define LEVEL_HEADER_WARPZONES_OFFSET 528
#define LEVEL_HEADER_WARPZONES_OFFSET_SIZE OFFSET_SIZE

#define LEVEL_HEADER_WARPZONES_LEN_OFFSET 532
#define LEVEL_HEADER_WARPZONES_LEN_SIZE LEN_SIZE

//========== METADATA-PLAYER
#define LEVEL_HEADER_PLAYER_OFFSET 536
#define LEVEL_HEADER_PLAYER_OFFSET_SIZE OFFSET_SIZE

#define LEVEL_HEADER_PLAYER_LEN_OFFSET 540
#define LEVEL_HEADER_PLAYER_LEN_SIZE LEN_SIZE

//========== METADATA-ITEMS
#define LEVEL_HEADER_ITEMS_OFFSET 544
#define LEVEL_HEADER_ITEMS_OFFSET_SIZE OFFSET_SIZE

#define LEVEL_HEADER_ITEMS_LEN_OFFSET 548
#define LEVEL_HEADER_ITEMS_LEN_SIZE LEN_SIZE

//========== METADATA-EXTENSIONS
#define LEVEL_HEADER_EXTENSION_OFFSET 552
#define LEVEL_HEADER_EXTENSION_OFFSET_SIZE OFFSET_SIZE

#define LEVEL_HEADER_EXTENSION_LEN_OFFSET 556
#define LEVEL_HEADER_EXTENSION_LEN_SIZE LEN_SIZE

#define LEVEL_HEADER_SIZE 560
#define LEVEL_DATA_OFFSET LEVEL_HEADER_SIZE

void load_level_file(const char *name, int level[CELL_COUNT][CELL_COUNT]);
void save_level_file(const char *name, int level[CELL_COUNT][CELL_COUNT]);

#endif
